apiVersion: v1
kind: Service
metadata:
  name: oncall
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: oncall
    version: green # blue 
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
